version: '3.8'

services:
  react-app:
    build: .
    container_name: rogram
    restart: always
    ports:
      - "${PORT:-2053}:${PORT:-2053}"
    volumes:
      - .:/app
    command: yarn start --host --port 2053